networks:
  caveo-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

services:
  postgres:
    image: postgres:17.1-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: caveo-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: caveo@2024
    ports:
      - "5432:5432"
    networks:
      - caveo-network

  caveo-bff:
    build:
      args:
        NODE_ENV: "production"
      context: .
      dockerfile: Dockerfile
    container_name: caveo-bff
    environment:
      APP_PORT: 8080
      APP_URL: 'https://caveo-bff-824385020093.us-central1.run.app'
      CAVEO_DEFAULT_PASSWORD: Caveo@2024
      COGNITO_CLIENT_ID: 1umo3njvmm0cl00ud7hpk3hoog
      COGNITO_REGION: us-east-2
      COGNITO_USER_POOL_ID: us-east-2_DMDaCuZl2
      NODE_ENV: production
      POSTGRES_DB: caveo-database
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: caveo@2024
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      SERVICE_ACCOUNT: '123412341234'
    image: us.gcr.io/vitorblsantos/caveo-bff:latest
    networks:
      - caveo-network
    ports:
      - "8080:8080"
    restart: on-failure
